language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - bash <(curl -s https://codecov.io/bash -s build/logs/)
#after_script:
#  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
